### ISSUE TITLE
The method to measure grasp difficulty

### ISSUE THREAD

**Issue by elevenjiang1** [dougsm/egad#8]
Hello,after reading your code and paper, I find that you use 75th grasp quality as grasp difficulty.
However, in my understanding, higher grasp quality corresponds to lower grasp difficulty?
I am not sure whether is my understanding of ferrari canny method wrong or I haven't found where you do the inverse between grasp quality and difficulty.

Best

**Comment by dougsm** [comment]
You're right, higher grasp quality corresponds to lower grasp difficulty with the ferrari canny metric.  I'm sorry, I don't understand what you mean by taking the inverse.  Can you elaborate?

**Comment by elevenjiang1** [comment]
Inverse means that when you rank the difficulty, maybe you need a function like difficulty=1/(quality), so that you can rank the difficulty.However, I haven't find this in your code, could you tell me where you do that?

For more detail, you get the 75th ferrair_canny quality (define as ```q75```) in dexnet_grasp_rank_interface.py, then seems directly use it as grasp difficulty (define as ```dexnet_return```) in generate_dataset.py. May be I lost something?


Thanks for your quick reply~

**Comment by elevenjiang1** [comment]
Sorry, but any reply for my question?
More detail, the code in function _update_pool_new_meshes( ) use the dexnet_return as difficulty, but this may be still quality?
```python
#here res is give back from pool_compare( ), which are diversity, m.complexity, dexnet_return, dists_all
for (nmidx, nmp), (gidx, g), (diversity, complexity, difficulty, similarities) in zip(new_mesh_paths,  kept_genomes, res):
```
Thank you~

**Comment by dougsm** [comment]
Hi, thanks for the clarification.  I see you are referring to the same vale being called "quality" in one side and "difficulty" in the other, and can see why that is a bit confusing. Sorry about that.

The grasp quality value is simply scaled to the number of bins in the search space (0 to 25 in this case), so that it is grouped with items of a similar difficulty.  
https://github.com/dougsm/egad/blob/264ac921eebad30ed2e14cab98525811f8380704/scripts/generate_dataset.py#L482

In this case the most difficult (lowest quality metric) are in bin zero, and the "easiest" in bin 24.  One could invert this order to avoid some confusion, but at the end of the day the results won't change, just the order of the cells. 

Hope that clears it up. 🙂

**Comment by elevenjiang1** [comment]
Okay, I get it.
Thank you very much~
